import {File} from '@asyncapi/generator-react-sdk'
import {CommonModel, GoGenerator} from '@asyncapi/modelina'

/**
 * @param {{}} asyncapi
 * @param {{[key: string]: any}} params
 */
export default async function ({asyncapi, params}) {
  const generator = new GoGenerator()
  const typeName = 'ChannelName'

  const m = new CommonModel()

  m.$id = typeName
  m.type = 'string'
  m.enum = Object.keys(asyncapi.channels())

  const models = await generator.generate(m)

  let content = ''

  models.forEach(model => {
    content += `${model.result}\n`
  })

  return (
    <File name="channels.gen.go">
      {`// Code generated by "asyncapi/generator"; DO NOT EDIT.

package ${params.packageName}

${content.replaceAll(/^\s{2}/gm, "\t").trim()}

// String returns the string representation of the channel name.
func (c ${typeName}) String() string { return string(c) }
`}
    </File>
  )
}
