import {File} from '@asyncapi/generator-react-sdk'
import {FormatHelpers} from '@asyncapi/modelina'

/**
 * @param {{}} asyncapi
 * @param {{[key: string]: any}} params
 */
export default async function ({asyncapi, params}) {
  const servers = asyncapi.servers()
  let content = ''

  for (const serverName in asyncapi.servers()) {
    const server = servers[serverName]
    const vars = []

    if (server.hasVariables()) {
      for (const variableName in server.variables()) {
        vars.push(variableName)
      }
    }

    let url = servers[serverName].url()

    vars.forEach((variable) => {
      url = url.replace(`{${variable}}`, `" + ${variable} + "`)
    })

    url = `"${url}"`.replaceAll(' + ""', '').replaceAll('"" + ', '') // cleanup

    const funcName = 'Get' + FormatHelpers.toPascalCase(serverName) + 'ServerURI'

    content += `// ${funcName} returns the URL for the ${serverName} server.
func ${funcName}(${vars.length > 0 ? vars.join(', ') + ' string' : ''}) string {
\treturn ${url}
}\n\n`
  }

  return (
    <File name="servers.gen.go">
      {`// Code generated by "asyncapi/generator"; DO NOT EDIT.

package ${params.packageName}

${content.trim()}
`}
    </File>
  )
}
