name: release

on:
  release: # Docs: <https://git.io/JeBz1#release-event-release>
    types: [published]

jobs:
  docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - {uses: gacts/github-slug@v1, id: slug}

      - uses: docker/setup-qemu-action@v2 # Action page: <https://github.com/docker/setup-qemu-action>

      - uses: docker/setup-buildx-action@v2 # Action page: <https://github.com/docker/setup-buildx-action>

      - uses: docker/login-action@v2 # Action page: <https://github.com/docker/login-action>
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3 # Action page: <https://github.com/docker/build-push-action>
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/spiral/asyncapi-go-template:${{ steps.slug.outputs.version }}
            ghcr.io/spiral/asyncapi-go-template:${{ steps.slug.outputs.version-major }}.${{ steps.slug.outputs.version-minor }}
            ghcr.io/spiral/asyncapi-go-template:${{ steps.slug.outputs.version-major }}
            ghcr.io/spiral/asyncapi-go-template:latest

  package:
    name: Publish NPM package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: {node-version: 19, registry-url: 'https://npm.pkg.github.com', scope: '@spiral'}

      - {uses: gacts/github-slug@v1, id: slug}

      - run: npm version --no-commit-hooks --no-git-tag-version '${{ steps.slug.outputs.version }}'

      - run: npm ci

      - run: npm publish --access public
        env: {NODE_AUTH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'}
